development:
  host: <%= ENV["DB_HOST"] %> 
  username: <%= ENV["DB_USERNAME"] %> 
  password: <%= ENV["DB_PASSWORD"] %>
  adapter: postgresql
  database: <%= ENV["DB_NAME"] %> 
staging:
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  adapter: postgresql
  database: <%= ENV["DB_NAME"] %>
production:
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %> 
  password: <%= ENV["DB_PASSWORD"] %>
  adapter: postgresql
  database: <%= ENV["DB_NAME"] %> 

