# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00582889e8c488aab49e5f6440a139aaf2df14ab972b36a49802941c8a918d28b76459c47c0de61b93ab67a75355ff9e433d82981543bc9d9a14d2cf821f09bd
  pagseguro_email: ebecker@webholdingusa.com
  pagseguro_token: 3F0DC9752E4C46A6AD7B6EECE6E2FD4E

test:
  domain_name: example.com
  secret_key_base: 4c967af0353fa4e691ffd090101117aacf3ca7648f8101c56af4b8dc2b65a6d2cecf08b97805a50df3c4e58709966d2edd6687bf40a4d29019a11800156a59e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  pagseguro_token: <%= ENV["PAGSEGURO_TOKEN"] %>
  pagseguro_email: <%= ENV["PAGSEGURO_EMAIL"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  pagseguro_token: <%= ENV["PAGSEGURO_TOKEN"] %>
  pagseguro_email: <%= ENV["PAGSEGURO_EMAIL"] %>
